apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::295323642826:role/eksctl-myCluster-nodegroup-ng-64e-NodeInstanceRole-NO26IGUV4CKW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::295323642826:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-21T01:51:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1301"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 073c6710-efd5-4cb9-b63a-8aba61022e6f
